networks:
  dev:
    driver: bridge
volumes:
  firebase-emulators-cache:
  clarinet_var_lib_docker:
services:
  dev:
    container_name: dev
    image: ${BUILDER_IMAGE:-europe-west1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT_ID}/docker-repository-public/${GOOGLE_CLOUD_PROJECT_ID}:builder-latest}
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD}
      MAKE_DEV_ON_START: ${MAKE_DEV_ON_START:-true}
    volumes:
      - ${PWD}:${PWD}:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    working_dir: ${PWD}
    command: |
      bash -c '
      make docker-sock
      if [ "$${MAKE_DEV_ON_START}" = "true" ] ; then
        make dev
        if [ "$${MAKE_LOCAL_APPLICATION_TESTS_RUN_ON_START}" = "true" ] ; then
          [ "$${LOCAL_LOCAL_ANDROID_STUDIO_BUILD_APK_ON_START}" = "true" ] && \
            make -j \
              application-mobile-flutter-build-apk \
              # android-studio-emulator-restart
          make application-mobile-apk-run &
          until make local-application-tests-check-env ; do
            echo "[application-tests] Waiting for environment to be ready..."
            sleep 5
          done
          make application-tests-robot-framework-all-run
        fi
      fi
      sleep infinity
      '
    networks:
      dev:
        aliases:
          - devcontainer

  application-backend:
    restart: unless-stopped
    image: ${APPLICATION_BACKEND_IMAGE:-europe-west1-docker.pkg.dev/moov-438615/docker-repository/utrade:application-backend-latest}
    build:
      context: ${APPLICATION_DIR}
      dockerfile: backend/Dockerfile
      args:
        builder_image: ${BUILDER_IMAGE}

    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/workspaces/refactored-winner/.devcontainer/gcloud/infra/application_default_credentials.json}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-${GOOGLE_CLOUD_PROJECT_ID}}
      GCLOUD_PROJECT_ID: ${GCLOUD_PROJECT_ID:-${GOOGLE_CLOUD_PROJECT_ID}}
      VEGETABLE_IMAGES_BACKEND_PUBSUB_SUBSCRIPTION: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_VALIDATED_BACKEND_SUBSCRIPTION:-vegetable-images-validated-backend}
      UI_CONFIG_FIREBASE_SECRET_ID: ${UI_CONFIG_FIREBASE_SECRET_ID:-projects/${GOOGLE_CLOUD_PROJECT_ID}/secrets/firebase-config-web/versions/2}
      UI_CONFIG_GOOGLEMAPS_SECRET_ID: ${UI_CONFIG_GOOGLEMAPS_SECRET_ID:-projects/${GOOGLE_CLOUD_PROJECT_ID}/secrets/google-maps-api-key/versions/1}
      VEGETABLE_CREATED_IMAGES_MODERATOR_PUBSUB_TOPIC: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_CREATED_TOPIC:-vegetable-images-created}
      VEGETABLE_VALIDATED_IMAGES_BACKEND_PUBSUB_SUBSCRIPTION: ${LOCAL_FIREBASE_EMULATORS_PUBSUB_VEGETABLE_IMAGES_VALIDATED_BACKEND_SUBSCRIPTION:-vegetable-images-validated-backend}
      VEGETABLE_VALIDATED_IMAGES_CDN_PREFIX_URL: ${LOCAL_FIREBASE_EMULATORS_VEGETABLE_IMAGES_CDN_PREFIX_URL:-https://vegetable-images-cdn-prefix-url}
      VAULT_ADDR: http://vault-dev:8200
      VAULT_TOKEN: root
    volumes:
      - ${PWD}:${PWD}:cached
    networks:
      - dev

  firebase-emulators:
    container_name: firebase-emulators
    image: ${FIREBASE_EMULATORS_IMAGE:-europe-west1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT_ID}/docker-repository-public/${GOOGLE_CLOUD_PROJECT_ID}:firebase-emulators-latest}
    # Cannot build while Dockerfile base image (see FROM ...) is using new local builder image (for conveniance and accuracy) that could not be pulled yet.
    # build: NOT
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD}
      FIREBASE_AUTH_EMULATOR_HOST: http://localhost:9099
      FIREBASE_PUBSUB_EMULATOR_HOST: http://localhost:8085
      FIRESTORE_EMULATOR_HOST: http://localhost:8090
    volumes:
      - ${HOST_PWD:-${PWD}}:${PWD}:cached
      # - firebase-emulators-cache:/home/devuser/.cache/firebase/emulators
    working_dir: ${PWD}
    command: |
      bash -c '
      set -eu
      sleep infinity
      '
    networks:
      dev:

  clarinet-devnet:
    container_name: clarinet-devnet
    privileged: true
    tty: true
    image: ${CLARINET_DEVNET_IMAGE:-europe-west1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT_ID}/docker-repository-public/${GOOGLE_CLOUD_PROJECT_ID}:clarinet-latest}
    # Cannot build while Dockerfile base image (see FROM ...) is using new local builder image (for conveniance and accuracy) that could not be pulled yet.
    # build: NOT
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD}
      DOCKER_HOST: "unix:///run/user/1000/docker.sock"
      LOCAL_CLARINET_DEVNET_CONTAINER_CACHE: ${LOCAL_CLARINET_DEVNET_CONTAINER_CACHE:-${PWD}/local/.containers/clarinet-devnet}
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - ${HOST_PWD:-${PWD}}:${PWD}:cached
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    working_dir: ${PWD}
    command: |
      bash -c '
      set -eu
      make local-clarinet-devnet-start
      sleep infinity
      '
    networks:
      dev:
  android-studio:
    container_name: android-studio
    cap_add:
      - SYS_ADMIN
    image: ${ANDROID_STUDIO_IMAGE:-europe-west1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT_ID}/docker-repository-public/${GOOGLE_CLOUD_PROJECT_ID}:android-studio-latest}
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD}
      APK_PATH: ${LOCAL_ANDROID_STUDIO_APK_PATH:-mobile/build/app/outputs/flutter-apk/app-debug.apk}
      # DISPLAY_RESOLUTION: "${DISPLAY_RESOLUTION:-1920x1080}"
      DISPLAY_RESOLUTION: 1920x1080
      DISPLAY_NUMBER: "${DISPLAY_NUMBER:-:20}"
      DISPLAY: "${DISPLAY:-:20}"
      FLUTTER: flutter
      CHROME_LOG_FILE: /tmp/chrome_debug.log
      LOCAL_ANDROID_STUDIO_LOG_LEVEL: DEBUG
      LOCAL_ANDROID_STUDIO_ENV_SETUP: ${LOCAL_ANDROID_STUDIO_ENV_SETUP:-false}
      LOCAL_ANDROID_STUDIO_CONTAINER_CACHE: ${LOCAL_ANDROID_STUDIO_CONTAINER_CACHE:-${PWD}/local/.containers/android-studio}
      LOCAL_ANDROID_STUDIO_ON_START: ${LOCAL_ANDROID_STUDIO_ON_START:-false}
      LOCAL_ANDROID_GPU_MODE: ${LOCAL_ANDROID_STUDIO_ANDROID_GPU_MODE:-swiftshader_indirect}
      ANDROID_AVD_NAME: ${LOCAL_ANDROID_STUDIO_ANDROID_AVD_NAME:-Pixel_6_Playstore}
      LOCAL_APPLICATION_TESTS_MOBILE_IMAGES_DIR: ${PWD}/application/tests/mobile_images

    privileged: true
    volumes:
      - ${HOST_PWD:-${PWD}}:${PWD}:cached
    devices:
      - /dev/kvm
      - /dev/nvidia0
    runtime: nvidia
    shm_size: "8gb"
    group_add:
      - render
      - kvm
      - sgx
    working_dir: ${PWD}/application/mobile
    networks:
      dev:
    command: |
      bash -c '
      set -eu
      sleep infinity
      '
  vault-dev:
    container_name: vault-dev
    image: ${VAULT_DEV_IMAGE:-europe-west1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT_ID}/docker-repository-public/${GOOGLE_CLOUD_PROJECT_ID}:vault-dev-latest}

    cap_add:
      - IPC_LOCK
    environment:
      HOST_PWD: ${PWD}
      VAULT_DATA: ${PWD:-/workspaces}/.containers/vault/file
      VAULT_CONFIG: ${PWD:-/workspaces}/.containers/vault/config
      VAULT_AUDIT: ${PWD:-/workspaces}/.containers/vault/audit
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - ${HOST_PWD:-${PWD}}:${PWD}:cached
    working_dir: ${PWD}/application
    command: |
      bash -c '
      set -eu
      ./vault-init.sh
      sleep infinity
      '
    networks:
      dev:

  application-tests:
    container_name: application-tests
    image: ${APPLICATION_TESTS_IMAGE:-europe-west1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT_ID}/docker-repository-private/${GOOGLE_CLOUD_PROJECT_ID}:application-tests-latest}
    environment:
      APPLICATION_BACKEND_URL_DEBUG: http://devcontainer:8888
      HOST_PWD: ${PWD}
      LOCAL_APPLICATION_TESTS_DIR: ${PWD}/application/tests
      STORAGE_EMULATOR_HOST: http://${FIREBASE_STORAGE_EMULATOR_HOST:-firebase-emulators:9199}
    env_file:
      - .env
    volumes:
      - ${HOST_PWD:-${PWD}}:${PWD}:cached
    networks:
      dev:
    working_dir: ${PWD}/application/tests
    tty: true
    command: |
      bash -c '
      set -eu
      
      sleep infinity
      '
